### PR TITLE
#1923 fix concurrency issue

### LINKED ISSUE #1923: Can not access service level variable concurrently inside resource
When accessing the below resource concurrently, response value get corrupted. 

import ballerina.lang.message;

@http:BasePath("/productsservice")
service productmgt {

    xml payload = `<product>name</product>`;

    @http:GET
    resource product (message m) {

    message response = {};
    message:setXmlPayload(response, payload);

    reply response;
    }

}

### PR DESCRIPTION
**Pull request by kasunbg**
Fixes #1923

### CODE REVIEW

**Comment by SupunS** [comment]
We found out that this issue (#1923) occurs due to service level/ connector level variables are shared among resources/actions respectively, and when trying to access those variables with multiple threads at once, such concurrency issues occurs.

I think we need to fix this issue for all service level/connector level variables at the executor level, probably by introducing synchronizing/locking mechanism.

**Comment by isudana** [comment]
Agree with Supun. I think we need to have a discussion on concurrency handling of service and resource scope varibales.

**Comment by lankavitharana** [comment]
So can't we simply state that service level variables needs to be static and cannot modify concurrently?(means cannot modify within resources, only read is possible) 
in this case, xml is not static(since it's kind of streaming) and what he needs to do is define the xml value as a String and create the xml within the resource.

If we need to make the xml a static object, then one way is to keep a static string within the xml and use that to return an xml object when required. but this may increase the memory usage because it keeps two copies

**Comment by kasunbg** [comment]
In this particular case, the issue is that the BXML service-level variable also acts as a MessageDataSource for CarbonMessage. Hence, as you see in [1], it contains an outputStream instance which is the response output stream. 

This is obviously not correct, and can lead to concurrency issues when multiple request threads come and set its outputStream!!

In the above fix, I have cloned the BXML instance before setting it as a messageDataSource because BXML plays two acts.

https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-core/src/main/java/org/ballerinalang/model/values/BXML.java#L36

**Comment by kasunbg** [comment]
@lankavitharana You are asking to make the variable immutable if we set them as global variables isn't it? We need think through the implications of such a design before doing that..

**Comment by sameera-jayasoma** [comment]
We need to synchronize all the service level variables in order to prevent this issue. This needs be fixed for all the service level variables.

**Pull request closed without merging**
