### PR TITLE
Format sample codes

### PR DESCRIPTION
**Pull request by Shan1024**
This PR will format sample Ballerina codes in the **getting_started** directory.

### CODE REVIEW

**Comment by chanakaudaya** [comment]
@Shan1024 We have formatted these samples to make sure the debugger works with these samples. We have a limitation in the grammar at the moment which cannot process new lines. Hence, this PR cannot be merged until we get that fixed at the grammar level.

**Comment by hasithaa** [comment]
@Shan1024 , Could you please fix conflicts. ? Since whitespace support is added to composer, we should be able to merge this.

**Comment by Shan1024** [comment]
@hasithaa : Conflicts are resolved. Please review and merge.

**Comment by chanakaudaya** [comment]
We have moved the examples to ballerina-by-example site and all the samples are updated. Hence closing this PR.

**Pull request closed without merging**
