### PR TITLE
Implement null value assignment for reference type variable

### LINKED ISSUE #863: Add "null" or "nil" support to Ballerina language

### PR DESCRIPTION
**Pull request by nuwanw**
Fixes #863 , As bellow a null can be assigned to a reference type variable
function nullCheck ()(boolean) {
xml x;
x = null;
if (x == null) {
system:println("x is null");
}
return true;
}

As bellow null value can be return
return null;

### CODE REVIEW

**Comment by chanakaudaya** [comment]
Following program throws an internal ballerina cast error message. Better throw specific ballerina error message (without exposing internal ballerina details)

```
import ballerina.lang.system;
import ballerina.lang.messages;

function main(string[] args) {
  string s;
  xml x;
  json j;
  message m;
  s = messages:getStringPayload(m);
  system:println(s);
  system:println(x);
  system:println(j);
}
```

**Comment by chanakaudaya** [comment]
Following programs throw internal casting errors.

```
import ballerina.lang.system;
import ballerina.lang.messages;

function main(string[] args) {
  xml x;
  json j;
  xmlTest(x);
  jsonTest(j);
}

function xmlTest(xml m) {
  xml x = m;
  message msg = {};
  messages:setXmlPayload(msg, x);
}

function jsonTest(json m) {
  json x = m;
  message msg = {};
  messages:setJsonPayload(msg, x);
}
```

**Comment by chanakaudaya** [comment]
Following code also prints internal casting errors.
```
  json j;
  xml x = (xml)j;
```
Below error is thrown
```
error in ballerina program: org.ballerinalang.model.values.BNull cannot be cast to org.ballerinalang.model.values.BJSON
	 at ballerina.lang.typemappers:.json->.xml(null-value-test.bal:10)
	 at main(null-value-test.bal:4)
```

**Comment by nuwanw** [comment]
Fixed in 335dd359cfc6f1df1ee8f36478da856c7e46b48b and 8df6f8d25490a6fe165b74e3c2706d02bec6c209

**Comment by sameera-jayasoma** [comment]
This feature has been added the language recently. Therefore closing this PR. Thanks for your contribution

**Pull request closed without merging**
